# Generated by Django 5.1.15 on 2026-04-06 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.DateTimeField()),
                ('pack_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pack_title', models.CharField(blank=True, max_length=200, null=True)),
                ('pack_version', models.CharField(blank=True, max_length=100, null=True)),
                ('question_id', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('difficulty_tier', models.CharField(max_length=16)),
                ('finish_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('round_duration_seconds', models.PositiveIntegerField()),
                ('revealed_answer_indices', models.JSONField(default=list)),
                ('total_answers', models.PositiveSmallIntegerField()),
                ('points_awarded', models.PositiveSmallIntegerField()),
                ('remaining_time_at_finish', models.FloatField()),
                ('time_to_first_reveal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-client_timestamp'],
                'indexes': [models.Index(fields=['question_id', 'pack_id', 'pack_version'], name='editorial_c_questio_a9a2f4_idx'), models.Index(fields=['difficulty_tier', 'client_timestamp'], name='editorial_c_difficu_92e81a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('app_version', models.CharField(max_length=64)),
                ('pack_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pack_title', models.CharField(blank=True, max_length=200, null=True)),
                ('pack_version', models.CharField(blank=True, max_length=100, null=True)),
                ('question_id', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('difficulty_tier', models.CharField(max_length=16)),
                ('validation_style', models.CharField(max_length=16)),
                ('source_url', models.URLField()),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['question_id', 'pack_id', 'pack_version'], name='editorial_f_questio_ddfef4_idx'), models.Index(fields=['reason', 'received_at'], name='editorial_f_reason_030914_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=200)),
                ('pack_title', models.CharField(max_length=200)),
                ('pack_version', models.CharField(blank=True, default='', max_length=100)),
                ('question_id', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('difficulty_tier', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
                ('difficulty_score', models.PositiveSmallIntegerField()),
                ('validation_style', models.CharField(choices=[('factual', 'Factual'), ('editorial', 'Editorial'), ('humorous', 'Humorous')], max_length=16)),
                ('source_url', models.URLField()),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('quality', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('playtested', 'Playtested'), ('needs-refresh', 'Needs Refresh')], default='draft', max_length=32)),
                ('difficulty_notes', models.TextField(blank=True, default='')),
                ('editorial_notes', models.TextField(blank=True, default='')),
                ('answers_json', models.JSONField(default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pack_id', 'question_id'],
                'indexes': [models.Index(fields=['pack_id', 'question_id'], name='editorial_q_pack_id_aa2959_idx'), models.Index(fields=['is_current', 'quality'], name='editorial_q_is_curr_abfaf4_idx'), models.Index(fields=['category', 'difficulty_tier'], name='editorial_q_categor_a75c3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('pack_id', 'question_id', 'pack_version', 'content_hash'), name='unique_question_catalog_revision')],
            },
        ),
        migrations.CreateModel(
            name='QuestionReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', 'General'), ('editorial', 'Editorial'), ('playtest', 'Playtest')], default='general', max_length=32)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='editorial.questioncatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_review_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('request-changes', 'Request Changes'), ('mark-refresh-needed', 'Mark Refresh Needed'), ('mark-playtested', 'Mark Playtested')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='editorial.questioncatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_state', models.CharField(choices=[('proposed', 'Proposed'), ('in-review', 'In Review'), ('changes-requested', 'Changes Requested'), ('approved', 'Approved'), ('playtested', 'Playtested'), ('shipped', 'Shipped'), ('refresh-needed', 'Refresh Needed')], default='proposed', max_length=32)),
                ('requires_second_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('playtested_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_needed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_question_reviews', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_question_reviews', to=settings.AUTH_USER_MODEL)),
                ('question_catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_state', to='editorial.questioncatalog')),
            ],
            options={
                'ordering': ['question_catalog__pack_id', 'question_catalog__question_id'],
            },
        ),
    ]
